"use client";

import "./globals.css";
import { Inter } from "next/font/google";
import { JSXElementConstructor, ReactElement } from "react";
import ClientApp from "@/components/ClientApp";
import store from "@/redux/configureStore";
import { Provider } from "react-redux";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children:
    | ReactElement<any, string | JSXElementConstructor<any>>
    | ReactElement<any, string | JSXElementConstructor<any>>[];
}) {
  return (
    <html lang="en">
      <head>
        <style id="global-style"></style>
      </head>
      <body className={inter.className}>
        <Provider store={store}>
          <ClientApp>{children}</ClientApp>
        </Provider>
      </body>
    </html>
  );
}
